import Head from "next/head";
import styles from "../styles/Home.module.css";
import Map2 from "./newmap";
import { useState } from "react";

// Home component
export default function Home() {
  const [content, setContent] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Hurricane Projection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.fullwidth}>
        <Map2 />
      </div>
    </div>
  );
}
