import Head from "next/head";
import styles from "../styles/Home.module.css";
import Map from "./Map";
import { useState } from "react";
import ReactTooltip from "react-tooltip";

export default function Home() {
  const [content, setContent] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Hurricane Projection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.fullwidth}>
        <Map setTooltipContent={setContent} />
        <ReactTooltip>{content}</ReactTooltip>
      </div>
    </div>
  );
}
